export const LIST_ALL_ORDERS_REQUEST = 'LIST_ALL_ORDERS_REQUEST';
export const LIST_ALL_ORDERS_SUCCESS = 'LIST_ALL_ORDERS_SUCCESS';
export const LIST_ALL_ORDERS_FAIL = 'LIST_ALL_ORDERS_FAIL';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const LIST_MY_ORDERS_REQUEST = 'LIST_MY_ORDERS_REQUEST';
export const LIST_MY_ORDERS_SUCCESS = 'LIST_MY_ORDERS_SUCCESS';
export const LIST_MY_ORDERS_FAIL = 'LIST_MY_ORDERS_FAIL';
export const LIST_MY_ORDERS_RESET = 'LIST_MY_ORDERS_RESET';
